steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-app', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-app']

  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      [
        'apply',
        '--filename=k8s/',
        '--cluster=my-gke-cluster',
        '--location=asia-south1',
      ]
images:
  - 'gcr.io/$PROJECT_ID/my-app'

options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
