apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-blue-green-deployment
  labels:
    app: my-blue-green-site
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-blue-green-site
      version: blue
  template:
    metadata:
      labels:
        app: my-blue-green-site
        version: blue
    spec:
      containers:
        - name: my-blue-green-container
          image: asia-south1-docker.pkg.dev/my-gcp-learning-474617/blue-green-deployment
          ports:
            - containerPort: 80
