apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: nginx
    version: blue   # Switch this to "green" to deploy green version
  ports:
  - port: 80
    targetPort: 80
