apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
spec:
  type: LoadBalancer
  selector:
    app: my-nginx
  ports:
    - port: 80        # external port
      targetPort: 8080  # container port
