apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: nginx
    version: blue   # change to 'green' for blue-green switch
  ports:
  - port: 80
    targetPort: 80
